DSO-2499: Add validation of retrieved tag

diff --git a/.github/workflows/pipeline-template-go-ci-quorum.yaml b/.github/workflows/pipeline-template-go-ci-quorum.yaml
--- a/.github/workflows/pipeline-template-go-ci-quorum.yaml
+++ b/.github/workflows/pipeline-template-go-ci-quorum.yaml
@@ -302,6 +302,10 @@ jobs:
           fi
 
           echo "[INFO] Last tag found: $lastTag"
+          if [[ "$lastTag" == "partior-patch" ]]; then
+            echo "[ERROR] Detected failure in retrieving remote tag. Please check the log and resolve the issue before proceeding..."
+            exit 1
+          fi
           echo "QUORUM-VERSION=$lastTag" > ./app-version.cfg
           echo "last-tag=$lastTag" >> $GITHUB_OUTPUT
 
