DSO-1942 Try smarter tag checker

diff --git a/.github/workflows/pipeline-template-gradle-ci-tessera.yaml b/.github/workflows/pipeline-template-gradle-ci-tessera.yaml
--- a/.github/workflows/pipeline-template-gradle-ci-tessera.yaml
+++ b/.github/workflows/pipeline-template-gradle-ci-tessera.yaml
@@ -241,23 +241,40 @@ jobs:
         run: |
           #!/bin/bash
           set +e
-          tagListFile=taglist.txt
-          gh api repos/consensys/tessera/tags --jq '.[] | select(.name | test("^tessera-[0-9]+\\.[0-9]+\\.[0-9]+$")) | [.name,.commit.sha] | join(",")' > $tagListFile
+
+          upstreamTagChecker=${{ steps.pipeline-branch-config.outputs.origin-tag-checker_upstream_enabled }}
+          localFileTagChecker=${{ steps.pipeline-branch-config.outputs.origin-tag-checker.local-file_enabled }}
+          localFileTagCheckerFile=${{ steps.pipeline-branch-config.outputs.origin-tag-checker.local-file_file }}
           lastTag=partior-patch
-          for eachTagInfo in $(cat $tagListFile); 
-          do
-            currentTagName=$(echo $eachTagInfo | cut -d"," -f1 | xargs)
-            currentTagSha=$(echo $eachTagInfo | cut -d"," -f2 | xargs)
-            echo "[INFO] Checking currentTagSha for tag $currentTagName"
-            if (git cat-file -e $currentTagSha); then 
-              echo "[INFO] Found SHA hash";
-              lastTag=$(echo $currentTagName | sed "s/tessera-//g")
-              lastTag=${lastTag}_patch
-              break
-            else 
-              echo "[INFO] SHA hash not found.";
+
+          if [[ "$localFileTagChecker" == "true" ]]; then
+            if [[ ! -f "$localFileTagCheckerFile" ]]; then
+              echo "[ERROR] Unable to locate tag checker file: $localFileTagCheckerFile"
+              exit 1
             fi
-          done
+            lastTag=$(cat $localFileTagCheckerFile | xargs)
+            lastTag=${lastTag}_patch
+          fi
+
+          if [[ "$upstreamTagChecker" == "true" ]]; then
+            tagListFile=taglist.txt
+            gh api repos/consensys/tessera/tags --jq '.[] | select(.name | test("^tessera-[0-9]+\\.[0-9]+\\.[0-9]+$")) | [.name,.commit.sha] | join(",")' > $tagListFile
+            
+            for eachTagInfo in $(cat $tagListFile); 
+            do
+              currentTagName=$(echo $eachTagInfo | cut -d"," -f1 | xargs)
+              currentTagSha=$(echo $eachTagInfo | cut -d"," -f2 | xargs)
+              echo "[INFO] Checking currentTagSha for tag $currentTagName"
+              if (git cat-file -e $currentTagSha); then 
+                echo "[INFO] Found SHA hash";
+                lastTag=$(echo $currentTagName | sed "s/tessera-//g")
+                lastTag=${lastTag}_patch
+                break
+              else 
+                echo "[INFO] SHA hash not found.";
+              fi
+            done
+          fi
 
           echo "[INFO] Last tag found: $lastTag"
           echo "TESSERA-VERSION=$lastTag" > ./app-version.cfg
