DSO-2995: Enforce failure if upload failed (#10)

diff --git a/.github/workflows/pipeline-template-go-ci-quorum.yaml b/.github/workflows/pipeline-template-go-ci-quorum.yaml
--- a/.github/workflows/pipeline-template-go-ci-quorum.yaml
+++ b/.github/workflows/pipeline-template-go-ci-quorum.yaml
@@ -445,8 +445,12 @@ jobs:
 
           cd $baseDir
           echo [INFO] jfrog rt u $oriTarZipFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/$tarZipFilename --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $tarZipFilename
-          jfrog rt u $oriTarZipFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/$tarZipFilename --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $tarZipFilename
-          
+          jfrog rt u --fail-no-op $oriTarZipFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/$tarZipFilename --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $tarZipFilename
+          if [[ $? -gt 0 ]]; then
+            echo "[ERROR] Failed jfrog upload [$oriTarZipFilename]"
+            exit 1
+          fi
+
           echo [INFO] jfrog rt bp --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}
           jfrog rt bp "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT}
           jfrog rt sp \
diff --git a/.github/workflows/pipeline-template-quorum-signer-plugin-ci.yaml b/.github/workflows/pipeline-template-quorum-signer-plugin-ci.yaml
--- a/.github/workflows/pipeline-template-quorum-signer-plugin-ci.yaml
+++ b/.github/workflows/pipeline-template-quorum-signer-plugin-ci.yaml
@@ -354,8 +354,16 @@ jobs:
           groupID=$(echo $groupID | sed "s/\./\//g" | xargs)
 
           cd $baseDir
-          jfrog rt u $zipFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/ --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $zipFilename
-          jfrog rt u $checksumFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/ --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $checksumFilename
+          jfrog rt u --fail-no-op $zipFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/ --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $zipFilename
+          if [[ $? -gt 0 ]]; then
+            echo "[ERROR] Failed jfrog upload [$zipFilename]"
+            exit 1
+          fi
+          jfrog rt u --fail-no-op $checksumFilename ${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/ --build-name "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}" --build-number ${GITHUB_RUN_NUMBER}.${GITHUB_RUN_ATTEMPT} --module $checksumFilename
+          if [[ $? -gt 0 ]]; then
+            echo "[ERROR] Failed jfrog upload [$checksumFilename]"
+            exit 1
+          fi
           jfrog rt bp "${GITHUB_WORKFLOW} - ${{ env.ARTIFACT_BASE_NAME }}"
           jfrog rt sp \
             "${{ steps.pipeline-branch-config.outputs.artifact_packager_artifactory-repo }}/${groupID}/${{ env.ARTIFACT_BASE_NAME }}/${ARTIFACT_VERSION}/$zipFilename" \
